<a href="https://colab.research.google.com/github/Evertonvcf/Exerc-cios_DS/blob/main/Praticando_com_excel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:

df = pd.read_excel("Book.xlsx")

display(df)

         Data      Hora  Lote  Tipo   Cor  Dev Responsavel  Bat  Máquina
0  2024-03-10  00:00:00   123    110  560  NaN     Everton    1       22
1  2024-03-11  12:00:00   456    108  600  NaN        João    2       21
2  2024-03-12  13:00:00   789    105  540  NaN        José    3       10
3  2024-03-13  14:00:00   987    116  120  NaN      Carlos    4        9
4  2024-03-14  15:00:00   654    109  670  NaN     Michael    5        8
5  2024-03-15  16:00:00   321    110  570  NaN      Gordão    6        7
6  2024-03-16  00:00:00   123    110  560    x    Vinicius    7       22
7  2024-03-17  18:00:00   456    105  900  NaN     Everton    8       21
8  2024-03-18  19:00:00   789    110  120  NaN        João    1       10
9  2024-03-19  14:00:00   123    110  120  NaN        José    2        9
10 2024-03-20  15:00:00     9    110  120  NaN      Carlos    3        8
11 2024-03-21  15:10:00     8    110  120  NaN     Michael    4        7
12 2024-03-22  14:10:00     7    110  120  NaN      Gordão    5       22
13 2024-03-23  13:10:00     6    110  120  NaN    Vinicius    6       21
14 2024-03-24  15:00:00   654    109  670    x     Everton    7       10
15 2024-03-25  13:00:00   789    105  540    x        João    8        9
16 2024-03-26  18:00:00   456    105  900    x        José    9        8
17 2024-03-27  16:00:00     2    110  870  NaN      Carlos   10        7
18 2024-03-28  15:00:00     9    110  120    x     Michael   11       22

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Data         19 non-null     datetime64[ns]
 1   Hora         19 non-null     object
 2   Lote         19 non-null     int64
 3   Tipo         19 non-null     int64
 4   Cor          19 non-null     int64
 5   Dev          5 non-null      object
 6   Responsavel  19 non-null     object
 7   Bat          19 non-null     int64
 8   Máquina      19 non-null     int64
dtypes: datetime64[ns](1), int64(5), object(3)
memory usage: 1.5+ KB

In [ ]:
print(df.columns)

Index(['Data', 'Hora', 'Lote', 'Tipo ', 'Cor', 'Dev', 'Responsavel', 'Bat',
       'Máquina'],
      dtype='object')

In [ ]:
mascara_dup=df.duplicated(subset=['Hora','Lote','Tipo ','Cor'], keep=False)
dev_x = df['Dev'] =='x'
mascara_final = mascara_dup & dev_x
nomes_resp = df.loc[mascara_final,'Responsavel']
display(nomes_resp)

6     Vinicius
14     Everton
15        João
16        José
18     Michael
Name: Responsavel, dtype: object

In [ ]:
df_dup = df.loc[mascara_dup, ['Hora', 'Lote', 'Tipo ', 'Cor', 'Responsavel']]
display(df_dup)

        Hora  Lote  Tipo   Cor Responsavel
0   00:00:00   123    110  560     Everton
2   13:00:00   789    105  540        José
4   15:00:00   654    109  670     Michael
6   00:00:00   123    110  560    Vinicius
7   18:00:00   456    105  900     Everton
10  15:00:00     9    110  120      Carlos
14  15:00:00   654    109  670     Everton
15  13:00:00   789    105  540        João
16  18:00:00   456    105  900        José
18  15:00:00     9    110  120     Michael

In [ ]:

df_dup = df.loc[mascara_dup, ['Hora', 'Lote', 'Tipo ', 'Cor', 'Responsavel']]
mascara_dev_nao_x = df['Dev'] != 'x'

df['Produção'] = np.nan
df['Devolução'] = np.nan
df.loc[mascara_dup & dev_x, 'Devolução'] = df['Responsavel']
df.loc[mascara_dup & mascara_dev_nao_x, 'Produção'] = df['Responsavel']
display(df)

/tmp/ipython-input-35-460821193.py:6: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['Vinicius' 'Everton' 'João' 'José' 'Michael']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[mascara_dup & dev_x, 'Devolução'] = df['Responsavel']
/tmp/ipython-input-35-460821193.py:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['Everton' 'José' 'Michael' 'Everton' 'Carlos']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[mascara_dup & mascara_dev_nao_x, 'Produção'] = df['Responsavel']

,Data,Hora,Lote,Tipo,Cor,Dev,Responsavel,Bat,Máquina,Produção,Devolução
0,2024-03-10,00:00:00,123,110,560,NaN,Everton,1,22,Everton,NaN
1,2024-03-11,12:00:00,456,108,600,NaN,João,2,21,NaN,NaN
2,2024-03-12,13:00:00,789,105,540,NaN,José,3,10,José,NaN
3,2024-03-13,14:00:00,987,116,120,NaN,Carlos,4,9,NaN,NaN
4,2024-03-14,15:00:00,654,109,670,NaN,Michael,5,8,Michael,NaN
5,2024-03-15,16:00:00,321,110,570,NaN,Gordão,6,7,NaN,NaN
6,2024-03-16,00:00:00,123,110,560,x,Vinicius,7,22,NaN,Vinicius
7,2024-03-17,18:00:00,456,105,900,NaN,Everton,8,21,Everton,NaN
8,2024-03-18,19:00:00,789,110,120,NaN,João,1,10,NaN,NaN
9,2024-03-19,14:00:00,123,110,120,NaN,José,2,9,NaN,NaN
10,2024-03-20,15:00:00,9,110,120,NaN,Carlos,3,8,Carlos,NaN
11,2024-03-21,15:10:00,8,110,120,NaN,Michael,4,7,NaN,NaN
12,2024-03-22,14:10:00,7,110,120,NaN,Gordão,5,22,NaN,NaN
13,2024-03-23,13:10:00,6,110,120,NaN,Vinicius,6,21,NaN,NaN
14,2024-03-24,15:00:00,654,109,670,x,Everton,7,10,NaN,Everton
15,2024-03-25,13:00:00,789,105,540,x,João,8,9,NaN,João
16,2024-03-26,18:00:00,456,105,900,x,José,9,8,NaN,José
17,2024-03-27,16:00:00,2,110,870,NaN,Carlos,10,7,NaN,NaN
18,2024-03-28,15:00:00,9,110,120,x,Michael,11,22,NaN,Michael

In [ ]:
df['Nomes'] = df[ 'Produção'].fillna('') + df['Devolução'].fillna('')
display(df[['Hora', 'Lote', 'Tipo ','Cor', 'Nomes']])

        Hora  Lote  Tipo   Cor     Nomes
0   00:00:00   123    110  560   Everton
1   12:00:00   456    108  600
2   13:00:00   789    105  540      José
3   14:00:00   987    116  120
4   15:00:00   654    109  670   Michael
5   16:00:00   321    110  570
6   00:00:00   123    110  560  Vinicius
7   18:00:00   456    105  900   Everton
8   19:00:00   789    110  120
9   14:00:00   123    110  120
10  15:00:00     9    110  120    Carlos
11  15:10:00     8    110  120
12  14:10:00     7    110  120
13  13:10:00     6    110  120
14  15:00:00   654    109  670   Everton
15  13:00:00   789    105  540      João
16  18:00:00   456    105  900      José
17  16:00:00     2    110  870
18  15:00:00     9    110  120   Michael

In [ ]:
# Identifica as linhas duplicadas
mascara_dup = df.duplicated(subset=['Hora', 'Lote', 'Tipo ', 'Cor'], keep=False)

# Cria a coluna 'Duplicado' marcando as linhas duplicadas
df['Duplicado'] = np.nan
df.loc[mascara_dup, 'Duplicado'] = 'sim'

# Cria a coluna 'Responsaveis' para as linhas duplicadas
df['Responsaveis'] = np.nan

# Preenche a coluna 'Responsaveis' para as linhas duplicadas
for index, row in df[mascara_dup].iterrows():
    hora = row['Hora']
    lote = row['Lote']
    tipo = row['Tipo ']
    cor = row['Cor']

    # Encontra as linhas correspondentes
    linhas_correspondentes = df[(df['Hora'] == hora) &
                                 (df['Lote'] == lote) &
                                 (df['Tipo '] == tipo) &
                                 (df['Cor'] == cor)]

    responsavel_producao = linhas_correspondentes.loc[linhas_correspondentes['Dev'] != 'x', 'Responsavel'].iloc[0] if not linhas_correspondentes.loc[linhas_correspondentes['Dev'] != 'x'].empty else ''
    responsavel_devolucao = linhas_correspondentes.loc[linhas_correspondentes['Dev'] == 'x', 'Responsavel'].iloc[0] if not linhas_correspondentes.loc[linhas_correspondentes['Dev'] == 'x'].empty else ''

    # Combina os nomes e atualiza a coluna 'Responsaveis' nas linhas duplicadas
    df.loc[index, 'Responsaveis'] = f"{responsavel_producao} / {responsavel_devolucao}"

# Exibe o DataFrame com as novas colunas (filtrando apenas as linhas duplicadas, se desejar)
display(df)

/tmp/ipython-input-37-3525497154.py:6: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'sim' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[mascara_dup, 'Duplicado'] = 'sim'
/tmp/ipython-input-37-3525497154.py:28: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Everton / Vinicius' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[index, 'Responsaveis'] = f"{responsavel_producao} / {responsavel_devolucao}"

,Data,Hora,Lote,Tipo,Cor,Dev,Responsavel,Bat,Máquina,Produção,Devolução,Nomes,Duplicado,Responsaveis
0,2024-03-10,00:00:00,123,110,560,NaN,Everton,1,22,Everton,NaN,Everton,sim,Everton / Vinicius
1,2024-03-11,12:00:00,456,108,600,NaN,João,2,21,NaN,NaN,,NaN,NaN
2,2024-03-12,13:00:00,789,105,540,NaN,José,3,10,José,NaN,José,sim,José / João
3,2024-03-13,14:00:00,987,116,120,NaN,Carlos,4,9,NaN,NaN,,NaN,NaN
4,2024-03-14,15:00:00,654,109,670,NaN,Michael,5,8,Michael,NaN,Michael,sim,Michael / Everton
5,2024-03-15,16:00:00,321,110,570,NaN,Gordão,6,7,NaN,NaN,,NaN,NaN
6,2024-03-16,00:00:00,123,110,560,x,Vinicius,7,22,NaN,Vinicius,Vinicius,sim,Everton / Vinicius
7,2024-03-17,18:00:00,456,105,900,NaN,Everton,8,21,Everton,NaN,Everton,sim,Everton / José
8,2024-03-18,19:00:00,789,110,120,NaN,João,1,10,NaN,NaN,,NaN,NaN
9,2024-03-19,14:00:00,123,110,120,NaN,José,2,9,NaN,NaN,,NaN,NaN
10,2024-03-20,15:00:00,9,110,120,NaN,Carlos,3,8,Carlos,NaN,Carlos,sim,Carlos / Michael
11,2024-03-21,15:10:00,8,110,120,NaN,Michael,4,7,NaN,NaN,,NaN,NaN
12,2024-03-22,14:10:00,7,110,120,NaN,Gordão,5,22,NaN,NaN,,NaN,NaN
13,2024-03-23,13:10:00,6,110,120,NaN,Vinicius,6,21,NaN,NaN,,NaN,NaN
14,2024-03-24,15:00:00,654,109,670,x,Everton,7,10,NaN,Everton,Everton,sim,Michael / Everton
15,2024-03-25,13:00:00,789,105,540,x,João,8,9,NaN,João,João,sim,José / João
16,2024-03-26,18:00:00,456,105,900,x,José,9,8,NaN,José,José,sim,Everton / José
17,2024-03-27,16:00:00,2,110,870,NaN,Carlos,10,7,NaN,NaN,,NaN,NaN
18,2024-03-28,15:00:00,9,110,120,x,Michael,11,22,NaN,Michael,Michael,sim,Carlos / Michael

In [ ]:
df.drop(columns=['Nomes'])

,Data,Hora,Lote,Tipo,Cor,Dev,Responsavel,Bat,Máquina,Produção,Devolução,Duplicado,Responsaveis
0,2024-03-10,00:00:00,123,110,560,NaN,Everton,1,22,Everton,NaN,sim,Everton / Vinicius
1,2024-03-11,12:00:00,456,108,600,NaN,João,2,21,NaN,NaN,NaN,NaN
2,2024-03-12,13:00:00,789,105,540,NaN,José,3,10,José,NaN,sim,José / João
3,2024-03-13,14:00:00,987,116,120,NaN,Carlos,4,9,NaN,NaN,NaN,NaN
4,2024-03-14,15:00:00,654,109,670,NaN,Michael,5,8,Michael,NaN,sim,Michael / Everton
5,2024-03-15,16:00:00,321,110,570,NaN,Gordão,6,7,NaN,NaN,NaN,NaN
6,2024-03-16,00:00:00,123,110,560,x,Vinicius,7,22,NaN,Vinicius,sim,Everton / Vinicius
7,2024-03-17,18:00:00,456,105,900,NaN,Everton,8,21,Everton,NaN,sim,Everton / José
8,2024-03-18,19:00:00,789,110,120,NaN,João,1,10,NaN,NaN,NaN,NaN
9,2024-03-19,14:00:00,123,110,120,NaN,José,2,9,NaN,NaN,NaN,NaN
10,2024-03-20,15:00:00,9,110,120,NaN,Carlos,3,8,Carlos,NaN,sim,Carlos / Michael
11,2024-03-21,15:10:00,8,110,120,NaN,Michael,4,7,NaN,NaN,NaN,NaN
12,2024-03-22,14:10:00,7,110,120,NaN,Gordão,5,22,NaN,NaN,NaN,NaN
13,2024-03-23,13:10:00,6,110,120,NaN,Vinicius,6,21,NaN,NaN,NaN,NaN
14,2024-03-24,15:00:00,654,109,670,x,Everton,7,10,NaN,Everton,sim,Michael / Everton
15,2024-03-25,13:00:00,789,105,540,x,João,8,9,NaN,João,sim,José / João
16,2024-03-26,18:00:00,456,105,900,x,José,9,8,NaN,José,sim,Everton / José
17,2024-03-27,16:00:00,2,110,870,NaN,Carlos,10,7,NaN,NaN,NaN,NaN
18,2024-03-28,15:00:00,9,110,120,x,Michael,11,22,NaN,Michael,sim,Carlos / Michael